easy_admin:
    entities:
      - App\Entity\Addresses
      - App\Entity\Contacts
      - App\Entity\Dates
      - App\Entity\Entreprises
      - App\Entity\Mails
      - App\Entity\Missions
      - App\Entity\Phones
      - App\Entity\Technologies
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
